### ISSUE TITLE
pnpm install 爆 peer 依赖警告，装任何新的依赖也有

### ISSUE THREAD

**Issue by bicycleRiding** [tobe-fe-dalao/fast-vue3#24]
![image](https://user-images.githubusercontent.com/68490919/156508887-28153256-9323-4523-baac-b5371cfd5b77.png)

**Comment by BoBoDinachen** [comment]
将package.json中的less-loader依赖删除即可，再次执行pnpm install，见vite官方文档说明
![Snipaste_2022-03-30_16-42-06](https://user-images.githubusercontent.com/50007623/160789855-144dcbc5-f7be-4cb7-8b68-cfb19d3a84fa.png)
