### ISSUE TITLE
ui库换成elementui  报错

### ISSUE THREAD

**Issue by zhoyue** [tobe-fe-dalao/fast-vue3#36]
import { VueUseComponentsResolver, ElementPlusResolver } from 'unplugin-vue-components/resolvers'
export const AutoRegistryComponents = () => {
  return Components({
      ElementPlusResolver({ importStyle: 'sass' }),
      VueUseComponentsResolver(),
    ],
  })

**Comment by fonghehe** [comment]
贴一下报错信息

**Comment by fonghehe** [comment]
参考这个可解决：https://element-plus.org/zh-CN/guide/quickstart.html#%E7%94%A8%E6%B3%95
