### ISSUE TITLE
没有template分支

### ISSUE THREAD

**Issue by fangtianq** [tobe-fe-dalao/fast-vue3#43]
没有template分支。。

**Comment by fonghehe** [comment]
你说的是哪一个？

**Comment by fangtianq** [comment]
来信已经收到！！！！

**Comment by fangtianq** [comment]
![image](https://user-images.githubusercontent.com/12722882/177680175-f596933e-63a5-4936-9e5d-ba2c20dbccdd.png)

**Comment by hxzAugustinus** [comment]
换成main呗，
git clone -b main  https://github.com/tobe-fe-dalao/fast-vue3.git
反正只克隆一个分支就行

**Comment by fangtianq** [comment]
ok，o再研究一下
