### ISSUE TITLE
项目都跑不起来

### ISSUE THREAD

**Issue by yigezzd** [tobe-fe-dalao/fast-vue3#48]
==

**Comment by fonghehe** [comment]
一般来说是用了npm，建议提issue贴个截图

**Comment by fonghehe** [comment]
请使用yarn或者pnpm安装

**Comment by hellozxx** [comment]
你好，我也遇到了无法启动项目的问题，node版本为16.17.1
![image](https://user-images.githubusercontent.com/18497787/192738548-dfc85864-0461-4984-9c42-1b4e14986fec.png)
