### ISSUE TITLE
路由出错

### ISSUE THREAD

**Issue by scripted-C20** [tobe-fe-dalao/fast-vue3#50]
启动项目后告警,页面也没有显示
![image](https://user-images.githubusercontent.com/36700965/200566427-c4ae482f-107f-496e-8714-e9a310a5a6b7.png)

**Comment by scripted-C20** [comment]
测了一下发现是router/index引入的virtual:generated-pages的问题，去掉后手动接收root.ts（更改文件实例路径）后出现页面
![image](https://user-images.githubusercontent.com/36700965/200603138-1be6a2dc-3ae3-4b4b-bb5d-70fdb7e1e992.png)

**Comment by shewlong** [comment]
我也出现了该问题，初步猜测可能是node的版本与框架本身的版本不符合，造成pnpm导入的依赖有问题

**Comment by fonghehe** [comment]
这个是约定式路由的配置，按照配置即可
