### ISSUE TITLE
局域网打开白屏,报错

### ISSUE THREAD

**Issue by keven-one** [tobe-fe-dalao/fast-vue3#53]
node v16.16.0
clone 项目
pnpm i
pnpm run dev
ios14.8.1 safari 使用局域网访问
屏幕白屏，控制台报错。
<img width="999" alt="image" src="https://user-images.githubusercontent.com/9433531/205786174-0efe6081-5ee6-4212-932d-bf4ff129cea6.png">

使用官网`npm init vue@latest`命令
vite创建空的新项目，同样一个设备局域网访问。正常访问。

**Comment by fonghehe** [comment]
防火墙关了吗

**Comment by shiy-liu** [comment]
把代码里https证书那个插件注释掉试试呢
![image](https://user-images.githubusercontent.com/41949817/223120631-3843a575-3fbe-4d3a-b2cb-814cb896eabe.png)
