### ISSUE TITLE
直接运行项目会报错

### ISSUE THREAD

**Issue by Fourth-fresh-man** [tobe-fe-dalao/fast-vue3#56]
![image](https://user-images.githubusercontent.com/41275436/219844921-4d668429-fdb2-47d1-bded-29c475ea37ca.png)
这是我的环境
![image](https://user-images.githubusercontent.com/41275436/219844953-e4c9196b-4f87-4491-938c-7e5b00e724dd.png)

**Comment by MaleWeb** [comment]
缺少依赖包

**Comment by Fourth-fresh-man** [comment]
你好，我是直接yarn install下载依赖包的，但那个包仍然是缺失的吗？

**Comment by fonghehe** [comment]
启动指令是yarn dev
