### ISSUE TITLE
想问下什么版本node下载

### ISSUE THREAD

**Issue by jiangwentao064191** [tobe-fe-dalao/fast-vue3#57]
试了14.18 16.8 都是报错

**Comment by jiangwentao064191** [comment]
![image](https://user-images.githubusercontent.com/39212686/222110545-6f91cc1d-6fa9-4808-9328-57ca79591adc.png)
![image](https://user-images.githubusercontent.com/39212686/222110742-1a0b3477-372a-48d5-84f2-c40484bcc451.png)

**Comment by fonghehe** [comment]
不要用npm，文档里写了yarn和pnpm，随便用哪个都可以
