### ISSUE TITLE
直接使用Antd-vue的message组件，没有效果

### ISSUE THREAD

**Issue by liupeixin23** [tobe-fe-dalao/fast-vue3#58]
import { message } from 'ant-design-vue';
  message.success('This is a success message');
![image](https://user-images.githubusercontent.com/58200368/223091190-4590cd55-b50b-4735-8dc7-5e40cf5d9f53.png)

**Comment by shiy-liu** [comment]
得引入样式吧

**Comment by liupeixin23** [comment]
其他组件都可以正常使用，就这个组件有点问题，不是样式问题

**Comment by shiy-liu** [comment]
![image](https://user-images.githubusercontent.com/41949817/223411897-9aa10632-e801-4750-abe7-ffc096a64cb6.png)

**Comment by liupeixin23** [comment]
main.ts
![image](https://user-images.githubusercontent.com/58200368/223693671-b82b020e-40c5-4518-a944-ebd678024bea.png)
组件中
![image](https://user-images.githubusercontent.com/58200368/223693960-ae989fc7-1f9a-48df-bf7a-2b27e5b515c8.png)

已解决 ！ 感谢！
