### ISSUE TITLE
360提示，这个项目有木马

### ISSUE THREAD

**Issue by cscsb** [tobe-fe-dalao/fast-vue3#73]

**Comment by FenngChenn** [comment]
![Uploading image.png…]()
启动项目需要输入电脑密码，并且需要用户同意写入系统文件设置的权限，有点奇怪。没有同意后，终止了启动项目

**Comment by FenngChenn** [comment]
![Uploading image.png…]()
启动项目需要输入电脑密码，并且需要用户同意写入系统文件设置的权限，有点奇怪。没有同意后，终止了启动项目

**Comment by FenngChenn** [comment]
启动项目需要输入电脑密码，并且需要用户同意写入系统文件设置的权限，有点奇怪。没有同意后，终止了启动项目
![Uploading Snipaste_2024-05-31_15-14-34.png…]()

**Comment by fonghehe** [comment]
兄弟，避一下360，360疯起来自己的产品都杀的

**Comment by Holsonn** [comment]
> 兄弟，避一下360，360疯起来自己的产品都杀的

我的电脑管家、金山毒霸、瑞...也提示了（
