### ISSUE TITLE
跳到其他路由页面 刷新 会变成暗黑模式

### ISSUE THREAD

**Issue by XavierShi** [tobe-fe-dalao/fast-vue3#8]
![image](https://user-images.githubusercontent.com/16569751/151279111-8c67803a-fafe-43d2-af84-23a091e42052.png)
![image](https://user-images.githubusercontent.com/16569751/151279136-8d456207-e389-4a47-b2d8-bb03036c03c6.png)
原因貌似是根目录 index.html页面的这个class的问题
![image](https://user-images.githubusercontent.com/16569751/151279210-de23dba9-a2ff-4a65-8ad0-1a15e2567744.png)

**Comment by MaleWeb** [comment]
已修复

**Comment by MaleWeb** [comment]
已修复
